<?php

return [
			'menu'	=> [
					'login'			=> ['en' => 'Login', 'th' => 'เข้าสู่ระบบ'],
					'logout'		=> ['en' => 'Logout', 'th' => 'ออกจากระบบ'],
					'admin' 		=> ['en' => 'Admin', 'th' => 'ควบคุมระบบ'],
					'account'		=> ['en' => 'Account', 'th' => 'ผู้ใช้งาน'],
					'dashboard' 	=> ['en' => 'Page View', 'th' => 'สถิติการเข้าชม'],
					'my_profile' 	=> ['en' => 'My Profile', 'th' => 'ข้อมูลส่วนตัว'],
					'today_work' 	=> ['en' => 'Today Works', 'th' => 'งานวันนี้'],
					'job' 	 		=> ['en' => 'Jobs', 'th' => 'งานส่งของ'],
					'booking'		=> ['en' => 'Booking', 'th' => 'งานรับของ'],
					'connote'		=> ['en' => 'Connote', 'th' => 'ใบนำส่ง'],
					'shipping'		=> ['en' => 'Shipping', 'th' => 'งานส่งของ'],
					'user'			=> ['en' => 'User', 'th' => 'ผู้ใช้งาน'],
					'employee'		=> ['en' => 'Employee', 'th' => 'พนักงาน'],
					'customer'		=> ['en' => 'Customer', 'th' => 'ลูกค้า'],
					'position'		=> ['en' => 'Position', 'th' => 'ตำแหน่ง'],
					'point'			=> ['en' =>	'Point', 'th' => 'สถานที่รับสินค้า']
			],
			'lang'		=> [
					'text' 				=> ['en' => 'English', 'th'	=> 'ไทย'],
					'flag' 				=> ['en' => 'flag-icon-gb', 'th' => 'flag-icon-th'],
			],
			'warning' 	=> [
					'data_not_found'	=> ['en' => 'Data not found', 'th' => 'ไม่พบข้อมูล'],
					'thumbnail_warning'	=> ['en' => 'Image dimension should be wwwwwxhhhhh pixel and size have not exceed sssss. ', 'th' => 'รูปควรมีขนาด wwwwwxhhhhh พิเซล และมีขนาดไฟล์ไม่เกิน sssss'],
					'sorting_guide'		=> ['en' => 'Drag and Drop for sorting and then save to confirm. ', 'th' => 'ลากวางเรียงลำดับได้ตามต้องการ อย่าลืมกด Save เพื่อบันทึก'],
					'tag_guide'			=> ['en' => 'Comma-separated ', 'th' => "คั่นด้วยเครื่องลูกน้ำ ( , )"],
					'product_index'		=> ['en' => 'Save and back to list', 'th' => "บันทึกแล้วกลับไปหน้ารวมสินค้า"],
					'product_reload'	=> ['en' => 'Save and continue updating', 'th' => "บันทึกแล้วแก้ไขสินค้าต่อไป"],
			],
			'title'		=> [
					'dashboard' 		=> ['en' => 'Dashboard', 'th' => 'หน้าหลัก'],
					'role' 				=> ['en' => 'Role Management', 'th' => 'การจัดการสิทธิ์ผู้ใช้'],
					'about_product'		=> ['en' => 'Product Content Management', 'th' => 'จัดการเนื้อหาของสินค้า'],
					'product_list'		=> ['en' => 'Products', 'th' => 'รายการสินค้า'],
					'stock_manage' 		=> ['en' => 'Stocks', 'th' => 'จัดการคลังสินค้า'],
					'category' 			=> ['en' => 'Product Categories', 'th' => 'หมวดหมู่ของสินค้า'],
					'review_manage' 			=> ['en' => 'Reviews', 'th' => 'จัดการรีวิว'],
					'customer' 			=> ['en' => 'Customers', 'th' => 'ลูกค้า'],
					'about_us' 			=> ['en' => 'Our Story', 'th' => 'เรื่องราวของเรา'],
					'customer_history' 	=> ['en' => 'Customer History', 'th' => 'ประวัติลูกค้า'],
			],
			'btn'		=> [
					'add'		=> ['en' => 'Add', 'th' => 'เพิ่ม'],
					'create'	=> ['en' => 'Create', 'th' => 'สร้างใหม่'],
					'edit'		=> ['en' => 'Edit', 'th' => 'แก้ไข'],
					'remove'	=> ['en' => 'Remove', 'th' => 'ลบ'],
					'delete'	=> ['en' => 'Delete', 'th' => 'ลบทิ้ง'],
					'save'		=> ['en' => 'Save', 'th' => 'บันทึก'],
					'cancel'	=> ['en' => 'Cancel', 'th' => 'ยกเลิก'],
					'back'		=> ['en' => 'Back', 'th' => 'ย้อนกลับ'],
					'new'		=> ['en' => 'New', 'th' => 'สร้างใหม่'],
					'search'	=> ['en' => 'Search', 'th' => 'ค้นหา'],
					'sort'		=> ['en' => 'Sort by', 'th' => 'เรียงลำดับ'],
					'sorting'	=> ['en' => 'Sorting', 'th' => 'เรียงลำดับ'],
					'type'		=> ['en' => 'Type', 'th' => 'ประเภท'],
					'upload'	=> ['en' => 'Upload', 'th' => 'อัพโหลด'],
					'manage'	=> ['en' => 'Manage', 'th' => 'จัดการ'],
					'submit'	=> ['en' => 'Submit', 'th' => 'ตกลง'],
					'confirm'	=> ['en' => 'Confirm', 'th' => 'ยืนยัน'],
					'preview' 	=> ['en' => 'Preview', 'th' => 'ดูตัวอย่าง'],
					'update'	=> ['en' => 'Update', 'th' => 'อัพเดท'],
					'update_to'	=> ['en' => 'Update to', 'th' => 'อัพเดทเป็น'],
					'select'	=> ['en' => 'Select', 'th' => 'เลือก'],
					'yes'		=> ['en' => 'Yes', 'th' => 'ใช่'],
					'no'		=> ['en' => 'No', 'th' => 'ไม่ใช่'],
					'all'		=> ['en' => 'ALL', 'th' => 'ทั้งหมด'],
					'copy' 		=> ['en' => 'Copy', 'th' => 'คัดลอก'],
					'clear' 	=> ['en' => 'Clear', 'th' => 'ล้าง'],
					'view' 		=> ['en' => 'View', 'th' => 'ดูตัวอย่าง'],
					'detail'	=> ['en' => 'Detail', 'th' => 'รายละเอียด'],
					'publish'	=> ['en' => 'Publish', 'th' => 'เปิดให้แสดงหน้าเว็บ'],
					'order'		=> ['en' => 'Order', 'th' => 'เรียงลำดับ'],
					'unpublish'	=> ['en' => 'Unpublish', 'th' => 'ปิดไม่ให้แสดงหน้าเว็บ'],
					'post_fb'	=> ['en' => 'Post to Facebook', 'th' => 'โพสลง Facebook'],
					'or'		=> ['en' => 'Or', 'th' => 'หรือ'],
					'check'		=> ['en' => 'Check', 'th' => 'ตรวจสอบ'],
					'register'	=> ['en' => 'Register', 'th' => 'ลงทะเบียน'],
			],
			'booking' => [
					'booking' 	=> ['en' => 'Booking', 'th' => 'ส่งพัสดุ'],
					'cod' 		=> ['en' => 'COD', 'th' => 'เก็บเงินปลายทาง COD'],
			]
];